name: make-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Makefile
      run: |
        python3  -m venv venv
        . venv/bin/activate
        make install
