name: make-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run make setup
      run: make setup
    - name: Prepare venv
      run: |
        python3 -m venv venv
        . venv/bin/activate
    - name: Run make install
        run: make install
